### ISSUE TITLE
Doesn't detect songs

### ISSUE THREAD

**Issue by wioniqle-q** [WearifulCupid0/lavalink#1]
![image](https://user-images.githubusercontent.com/69215407/123685125-04d8bf00-d857-11eb-8c96-3db73961f533.png)

Hata: Error
Sonuç bulunamadı: no results found
Playlist: https://open.spotify.com/playlist/6LlLXu78D8CyyooJedrQoq

**Comment by WearifulCupid0** [comment]
No support for Spotify.
